### ISSUE TITLE
Add support for HTTPS into proxy

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#25]
Currently when try to connect to HTTPS source, show this error:
```

Wed, 10 May 2017 02:24:36 GMT sm:logger info: Listening.
{}
Wed, 10 May 2017 02:24:36 GMT sm:master:source_in SourceIn listening on 10101
info: Master now listening for slave connections. module=master_io
info: Listening.
Wed, 10 May 2017 02:24:36 GMT sm:logger debug: Parsing stream for la100.aac
{}
debug: Parsing stream for la100.aac
Wed, 10 May 2017 02:24:36 GMT sm:logger debug: Creating an unspecified source mount for la100.aac (via la100.aac).
{}
debug: Creating an unspecified source mount for la100.aac (via la100.aac).
Wed, 10 May 2017 02:24:36 GMT sm:logger event: Source Mount is initializing. { source_mount: 'la100.aac' }
key: 'la100.aac' } }
Wed, 10 May 2017 02:24:36 GMT sm:logger debug: Starting up master stream: la100.aac { opts:
event: Source Mount is initializing. source_mount=la100.aac
headers:
{ referer: 'https://la100.cienradios.com/player/la100/',
'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1' },
seconds: '900',
format: 'aac',
fallback: 'https://buecrplb01.cienradios.com.ar/la100.aac',
source_password: 'la100.aac',
{ root_route: true,
debug: Starting up master stream: la100.aac root_route=true, referer=https://la100.cienradios.com/player/la100/, user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1, seconds=900, format=aac, fallback=https://buecrplb01.cienradios.com.ar/la100.aac, source_password=la100.aac, key=la100.aac
Wed, 10 May 2017 02:24:36 GMT sm:logger event: Stream is initializing. { stream: 'la100.aac' }
Wed, 10 May 2017 02:24:36 GMT sm:logger info: Initializing RewindBuffer for master stream. { stream: 'la100.aac' }
event: Stream is initializing. stream=la100.aac
info: Initializing RewindBuffer for master stream. stream=la100.aac
Wed, 10 May 2017 02:24:36 GMT sm:logger debug: Setting up HLS Segmenter. { segment_duration: 30, stream: 'la100.aac', module: 'rewind' }
debug: Setting up HLS Segmenter. segment_duration=30, stream=la100.aac, module=rewind
debug: RewindBuffer got source event stream=la100.aac, module=rewind
Wed, 10 May 2017 02:24:36 GMT sm:logger debug: RewindBuffer got source event { stream: 'la100.aac', module: 'rewind' }
Wed, 10 May 2017 02:24:36 GMT sm:logger debug: ProxySource created for https://buecrplb01.cienradios.com.ar/la100.aac { stream: 'la100.aac',
uuid: '68763fd2-7c1d-4e65-9a56-7b7501578f67' }
debug: ProxySource created for https://buecrplb01.cienradios.com.ar/la100.aac stream=la100.aac, uuid=68763fd2-7c1d-4e65-9a56-7b7501578f67
Wed, 10 May 2017 02:24:36 GMT sm:logger debug: connecting to https://buecrplb01.cienradios.com.ar/la100.aac { stream: 'la100.aac',
uuid: '68763fd2-7c1d-4e65-9a56-7b7501578f67' }
debug: connecting to https://buecrplb01.cienradios.com.ar/la100.aac stream=la100.aac, uuid=68763fd2-7c1d-4e65-9a56-7b7501578f67


Wed, 10 May 2017 02:24:36 GMT sm:sources:proxy Connecting to https://buecrplb01.cienradios.com.ar/la100.aac
at Stream.<anonymous> (/srv/StreamMachine/js/src/streammachine/master/stream.js:133:20)
at new ClientRequest (_http_client.js:54:11)
at Object.exports.request (http.js:31:10)
at new Client (/srv/StreamMachine/node_modules/icy/lib/client.js:38:18)
at request (/srv/StreamMachine/node_modules/icy/lib/request.js:25:10)
at Object.get (/srv/StreamMachine/node_modules/icy/lib/get.js:26:13)
at ProxySource.module.exports.ProxySource.connect (/srv/StreamMachine/js/src/streammachine/sources/proxy.js:120:16)
at Domain.<anonymous> (/srv/StreamMachine/js/src/streammachine/sources/proxy.js:58:22)
Wed, 10 May 2017 02:24:36 GMT sm:sources:proxy Caught error: Error: Protocol "https:" not supported. Expected "http:" Error: Protocol "https:" not supported. Expected "http:"
at new ProxySource (/srv/StreamMachine/js/src/streammachine/sources/proxy.js:56:12)
at Domain.run (domain.js:221:14)



Wed, 10 May 2017 02:24:36 GMT sm:logger error: ProxySource encountered an error: Error making connection to Icecast proxy { domain:
Domain {
domain: null,
_events: { error: [Function] },
}, _eventsCount=1, _maxListeners=undefined, members=[], domainThrown=true, stream=la100.aac, uuid=68763fd2-7c1d-4e65-9a56-7b7501578f67
_maxListeners: undefined,
members: [] },
domainThrown: true,
stream: 'la100.aac',
uuid: '68763fd2-7c1d-4e65-9a56-7b7501578f67' }
error: ProxySource encountered an error: Error making connection to Icecast proxy domain=null, error=function (err) {
return _this._niceError(err);
_eventsCount: 1,
Wed, 10 May 2017 02:25:05 GMT sm:master:streamer Ping
Wed, 10 May 2017 02:25:35 GMT sm:master:streamer Ping
Wed, 10 May 2017 02:26:05 GMT sm:master:streamer Ping

```

**Comment by martindido** [comment]
#24

**Comment by cdgraff** [comment]
error: Unable to determine fallback source type for https://buecrplb01.cienradios.com.ar/la100.aac stream=la100.aac
