### ISSUE TITLE
SourceIn Fail

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#39]
When try to publish a PUSH stream fail to start and crash de app

```
  sm:logger debug: Incoming source attempt. +26ms { mode: 'sourcein' }
sourcein -- debug: Incoming source attempt.
  sm:master:source_in Parser request line: SOURCE /desa.mp3 HTTP/1.0 +1ms
  sm:master:source_in Parser request line: Authorization: Basic c291cmNlOmRlc2EubXAz +1ms
  sm:master:source_in Parser request line: ice-bitrate: 128 +0ms
  sm:master:source_in Parser request line: ice-name: Alejandro Ferrari's Broadcast +0ms
  sm:master:source_in Parser request line: ice-genre:  +0ms
  sm:master:source_in Parser request line: ice-description:  +0ms
  sm:master:source_in Parser request line: ice-url: http://www.rogueamoeba.com/nicecast/ +0ms
  sm:master:source_in Parser request line: ice-public: 1 +0ms
  sm:master:source_in Parser request line: User-Agent: aucast/1.0 +0ms
  sm:master:source_in Parser request line: Content-Type: audio/mpeg +0ms
  sm:master:source_in Parser request line:  +0ms
  sm:logger debug: ICY SOURCE attempt. +1ms { url: '/desa.mp3', mode: 'sourcein' }
sourcein -- debug: ICY SOURCE attempt. url=/desa.mp3
  sm:master:source_in Incoming source matched mount: desa.mp3 +0ms
  sm:logger debug: Trying to authenticate ICY source for desa.mp3 +0ms { mode: 'sourcein' }
sourcein -- debug: Trying to authenticate ICY source for desa.mp3
  sm:logger debug: ICY source authenticated for desa.mp3. +2ms { mode: 'sourcein' }
sourcein -- debug: ICY source authenticated for desa.mp3.
  sm:logger debug: New Icecast source. +1ms { source_mount: 'desa.mp3',
  uuid: 'aa689678-ae05-44ba-8bcb-068886278b53' }
debug: New Icecast source. source_mount=desa.mp3, uuid=aa689678-ae05-44ba-8bcb-068886278b53
_stream_readable.js:582
  dest.on('unpipe', onunpipe);
       ^

TypeError: Cannot read property 'on' of undefined
    at Socket.Readable.pipe (_stream_readable.js:582:8)
    at new IcecastSource (/srv/StreamMachine/js/src/streammachine/sources/icecast.js:43:20)
    at /srv/StreamMachine/js/src/streammachine/master/source_in.js:101:20
    at SourceIn.module.exports.SourceIn._trySource (/srv/StreamMachine/js/src/streammachine/master/source_in.js:119:14)
    at SourceIn._trySource (/srv/StreamMachine/js/src/streammachine/master/source_in.js:2:59)
    at IcyParser.<anonymous> (/srv/StreamMachine/js/src/streammachine/master/source_in.js:81:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at IcyParser.emit (events.js:211:7)
    at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.HEADER (/srv/StreamMachine/js/src/streammachine/master/source_in.js:244:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streammachine@0.7.2 start:dev: `DEBUG=* node ./js/streamer.js --config config/master-dev.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the streammachine@0.7.2 start:dev script.
```

**Comment by cdgraff** [comment]
Done! https://github.com/mediainbox/StreamMachine/pull/40
