### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#46]
Unexpected and uncaught greenlock.notify error:
TypeError: Cannot read property 'then' of undefined
    at rpc (/srv/StreamMachine/node_modules/@root/greenlock-express/master.js:137:17)
    at Worker.handleMessage (/srv/StreamMachine/node_modules/@root/greenlock-express/master.js:156:13)
    at Worker.emit (events.js:187:15)
    at Worker.EventEmitter.emit (domain.js:442:20)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:28:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:32073) UnhandledPromiseRejectionWarning: Error: worker rpc request timeout
    at Timeout._onTimeout (/srv/StreamMachine/node_modules/@root/greenlock-express/worker.js:70:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:32073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:32073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cdgraff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Greenlock Error](https://trello.com/c/rnnUhVrm/100-greenlock-error)

**Comment by cdgraff** [comment]
https://git.coolaj86.com/coolaj86/greenlock-express.js/issues/80
