### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#47]
TypeError: Cannot read property '1' of null
    at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.HEADER (/srv/StreamMachine/js/src/streammachine/master/source_in.js:242:39)
    at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.execute (/srv/StreamMachine/js/src/streammachine/master/source_in.js:175:25)
    at Socket.<anonymous> (/srv/StreamMachine/js/src/streammachine/master/source_in.js:62:32)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by cdgraff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SourceIn Icecast Error](https://trello.com/c/1Fh06cPB/102-sourcein-icecast-error)

**Comment by cdgraff** [comment]
```
0|c3-sm-master | sourcein -- debug: Incoming source attempt.
0|c3-sm-master | ///// ICY PARSER HEADER: Host: 64.225.62.32:8080
0|c3-sm-master | ///// ICY PARSER HEADER: User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
0|c3-sm-master | ///// ICY PARSER HEADER: Content-Length: 0
0|c3-sm-master | ///// ICY PARSER HEADER:
```

**Comment by cdgraff** [comment]
Headers correctos:
```

0|c3-sm-master | sourcein -- debug: Incoming source attempt.
0|c3-sm-master | ///// ICY PARSER HEADER: Authorization: Basic c291cmNlOjEyMzQ1
0|c3-sm-master | ///// ICY PARSER HEADER: Host: masterdo5.mediainbox.net:8080
0|c3-sm-master | ///// ICY PARSER HEADER: User-Agent: butt 0.1.20
0|c3-sm-master | ///// ICY PARSER HEADER: Content-Type: audio/mpeg
0|c3-sm-master | ///// ICY PARSER HEADER: ice-name: no name
0|c3-sm-master | ///// ICY PARSER HEADER: ice-public: 0
0|c3-sm-master | ///// ICY PARSER HEADER: ice-audio-info: ice-bitrate=128;ice-channels=2;ice-samplerate=44100
0|c3-sm-master | ///// ICY PARSER HEADER: Expect: 100-continue
0|c3-sm-master | ///// ICY PARSER HEADER:
0|c3-sm-master | sourcein -- debug: ICY SOURCE attempt. url=/stream
0|c3-sm-master | sourcein -- debug: ICY source attempted to connect to bad URL. url=/stream
```
