### ISSUE TITLE
If I disabled geolock into slave server, listening fail

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#5]
If I disabled geolock into slave server, got this error trying to play the stream

`
Error: Required DB not available. Possible types: ""
    at _getDb (/srv/StreamMachine/node_modules/maxmind/lib/lookup_service.js:34:9)
    at Object.exports.getCountry (/srv/StreamMachine/node_modules/maxmind/lib/lookup_service.js:203:12)
    at Server.module.exports.Server.isGeolocked (/srv/StreamMachine/js/src/streammachine/slave/server.js:242:25)
    at /srv/StreamMachine/js/src/streammachine/slave/server.js:74:21
    at paramCallback (/srv/StreamMachine/node_modules/express/lib/router/index.js:151:7)
    at param (/srv/StreamMachine/node_modules/express/lib/router/index.js:133:11)
    at pass (/srv/StreamMachine/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/srv/StreamMachine/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/srv/StreamMachine/node_modules/express/lib/router/index.js:33:10)
    at next (/srv/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
`

**Comment by comodinx** [comment]
Fixed in commit [a8c8a870f8bd7068c8fa776c303167021a17dcad](https://github.com/StreamMachine/StreamMachine/commit/a8c8a870f8bd7068c8fa776c303167021a17dcad)
