### ISSUE TITLE
Parsing ICY info headers

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/StreamMachine#8]
event: Promoting new source to active. source=Icecast (::ffff:190.225.166.25:54871), source_mount=cadena3.mp3
Master-5 /srv/StreamMachine/js/src/streammachine/master/source_in.js:242
Master-5         return this.info.headers[match[1].toLowerCase()] = match[2];
Master-5                                       ^
Master-5 TypeError: Cannot read property '1' of null
Master-5     at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.HEADER (/srv/StreamMachine/js/src/streammachine/master/source_in.js:242:39)
Master-5     at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.execute (/srv/StreamMachine/js/src/streammachine/master/source_in.js:175:25)
Master-5     at Socket.<anonymous> (/srv/StreamMachine/js/src/streammachine/master/source_in.js:62:32)
Master-5     at emitNone (events.js:67:13)
Master-5     at Socket.emit (events.js:166:7)
Master-5     at emitReadable_ (_stream_readable.js:419:10)
Master-5     at emitReadable (_stream_readable.js:413:7)
Master-5     at readableAddChunk (_stream_readable.js:164:13)
Master-5     at Socket.Readable.push (_stream_readable.js:111:10)
Master-5     at TCP.onread (net.js:531:20)
Master-5 adding Console transport

**Comment by cdgraff** [comment]
Long time without saw this error and we update ICY library too.
